MVC3.UI.MVC/Controllers/FiltersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC3.DATA.EF;//This is added for our EF domain models
using System.Data.Entity;//This is added for EF
using PagedList;//Added after NuGet PagedList
using PagedList.Mvc;//Added after NuGet PagedList.MVC

namespace MVC3.UI.MVC.Controllers
{
    public class FiltersController : Controller
    {
        private BookStorePlusEntities db = new BookStorePlusEntities();

        // GET: Filters
        public ActionResult Index()
        {

            return View();
        }

        //Servor Side Filter Action
        public ActionResult AuthorsQS(string searchFilter)
        {
            if (String.IsNullOrEmpty(searchFilter))
            {
                //If optional search isn't used, return all records

                return View(db.Authors.ToList());
            }
            else
            {
                //If optional search is used, compare it to the first and last name. Use Linq
                //This is a Method example, below this is a Keyword Syntax example
                string searchUpCase = searchFilter.ToUpper();
                List<Author> searchResults = db.Authors
                                             .Where(a => a.FirstName.ToUpper().Contains(searchUpCase)
                                             || a.LastName.ToUpper().Contains(searchUpCase))
                                             .OrderBy(a => a.FirstName)
                                             .ThenBy(a => a.LastName)
                                             .ToList();

                //Method syntax example above Or Query syntax example below
                List<Author> searchResult2 = (from a in db.Authors
                                              where a.FirstName.ToUpper().Contains(searchUpCase) ||
                                              a.LastName.ToUpper().Contains(searchUpCase)
                                              orderby a.FirstName, a.LastName
                                              select a).ToList();
                return View(searchResults);
            }
        }

        public ActionResult LabMagazinesQS(string searchFilter)
        {
            if (String.IsNullOrEmpty(searchFilter))
            {
                //If optional search isn't used, return all records

                return View(db.Magazines.ToList());
            }
            else
            {
                //If optional search is used, compare it to the first and last name. Use Linq
                //This is a Method example, below this is a Keyword Syntax example

                string searchUpCase = searchFilter.ToUpper();
                List<Magazine> searchResults = db.Magazines
                                             .Where(m => m.MagazineTitle.ToUpper().Contains(searchUpCase)
                                             || m.Category.ToUpper().Contains(searchUpCase))
                                             .OrderBy(m => m.MagazineTitle)
                                             .ThenBy(m => m.Category)
                                             .ToList();

                //Method syntax example above Or Query syntax example below
                //List<Author> searchResult2 = (from m in db.Magazines
                //                              where m.MagazineTitle.ToUpper().Contains(searchUpCase) ||
                //                              m.PublishRate.ToUpper().Contains(searchUpCase)
                //                              orderby m.MagazineTitle, m.PublishRate
                //                              select m).ToList();
                return View(searchResults);
            }
        }

        public ActionResult BooksMVCPaging(string searchString, string currentFilter, int page = 1)
        {
            int pageSize = 5;
            var books = db.Books.OrderBy(b => b.BookTitle).ToList();

            #region Search With Paging
            //We are tracking it's a new search(Go To Page 1 with results)
            //or if it's a previous search(track with current filter and use paging based on the last request)
            /*
             * In the Action-
             * SearchString only gets assigned new searches
             * If searchString has a value, then it is a search - update the page to 1(first page of results)
             * Else if searchString is null, assign searchString to use the currentFilter value ( either null/empty OR previously tracked old search)
             * 
             */

            #endregion

            if(searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            //Check if the searchString is not null or empty.
            //If it is NOT null use the filter to grab the new data set

            if (!String.IsNullOrEmpty(searchString))
            {
                books = (from b in books
                        where b.BookTitle.ToLower().Contains(searchString.ToLower())
                        orderby b.BookTitle
                         select b).ToList();
            }

            //Set up a ViewBag variable for passing currentFilter based on whatever searchString is now
            ViewBag.CurrentFilter = searchString;

            return View(books.ToPagedList(page, pageSize));
        }

        public ActionResult LabMagazinesMVCPaging(string searchString, string currentFilter, int page = 1)
        {
            int pageSize = 5;
            var magazines = db.Magazines.OrderBy(c => c.Category).ToList();

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                magazines = (from c in magazines
                             where c.Category.ToLower().Contains(searchString.ToLower())
                         orderby c.Category
                         select c).ToList();
            }

            ViewBag.CurrentFilter = searchString;

            return View(magazines.ToPagedList(page, pageSize));
        }
    }
}

MVC3.UI.MVC/Views/Filters/AuthorsQS.cshtml
@model IEnumerable<MVC3.DATA.EF.Author>

@{
    ViewBag.Title = "AuthorsQS";
}

<h2>@ViewBag.Title</h2>

<div class="row panel panel-primary">
    <br />
    <form action="AuthorsQS" method="get" class="form-horizontal pull-left">
        <div class="form-group">
            <div class="col-xs-offset-1 col-xs-11 col-sm-2">
                <label for="searchFilter">Search</label>
            </div>
            <div class="col-xs-offset-1 col-xs-11 col-sm-5">
                <input type="text" name="searchFilter" />
            </div>
            <div class="col-xs-offset-1 col-xs-11 col-sm-2">
                <input type="submit" value="Go!" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZipCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ZipCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>        
    </tr>
}

</table>

MVC3.UI.MVC/Views/Filters/BooksMVCPaging.cshtml
@*Updating with Paging List and usign below*@
@*@model IEnumerable<MVC3.DATA.EF.Book>*@
@model PagedList.IPagedList<MVC3.DATA.EF.Book>
@using PagedList.Mvc;

@{
    ViewBag.Title = "BooksMVCPaging";
}

<h2>@ViewBag.Title</h2>

@*Search Form with using Html.BeginForm*@
@using (Html.BeginForm("BooksMVCPaging", "Filters", FormMethod.Get))
{
    <p class="pull-right text-right">
        @*Set the text box for search but also track the last(aka current) search term applied
               (this is tracked with our ViewBag*@
        @*signature: ("Name",       "Current Value",                        htmlAttributes)*@
        @Html.TextBox("searchString", ViewBag.CurrentFilter as string, new { placeholder = "Search Title" })
        <input type="submit" value="Search" class="btn btn-primary" />
    </p>
}

@*Adding the Pager Code wherever we want it to show on the page*@
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("BooksMVCPaging",new { page, currentFilter = ViewBag.CurrentFilter }))
@*Toggle Disclaimer for no results*@
@if (Model.Count == 0)
{
    <p class="alert alert-warning">
        No Results meet your criteria
    </p>
}
else
{

<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.ISBN)*@
            @Html.DisplayFor(model => model.FirstOrDefault().ISBN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().BookTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().UnitsSold)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().PublishDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().BookStatus.BookStatusName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Genre.GenreName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Publisher.PublisherName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ISBN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BookTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitsSold)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PublishDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BookStatus.BookStatusName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre.GenreName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Publisher.PublisherName)
        </td>
    </tr>
}
</table>
}

MVC3.UI.MVC/Views/Filters/Index.cshtml
@{
    ViewBag.Title = "Search and Paging";
}

<h2>@ViewBag.Title</h2>

<div class="col-md-12">
    <h3>Server-side</h3>
    <p>
        @Html.ActionLink("Server-Side Querystring Search (Author Name)", "AuthorsQS", "Filters", null, new { @class = "btn btn-primary" })
    </p>
    <p>
        @Html.ActionLink("Lab: Server-Side Querystring Search (Magazine Category)", "LabMagazinesQS", "Filters", null, new { @class = "btn btn-primary" })
    </p>
    <p>
        @Html.ActionLink("Server-Side MVCPaging (Books)", "BooksMVCPaging", "Filters", null, new { @class = "btn btn-primary" })
    </p>
    <p>
        @Html.ActionLink("Lab: Server-Side MVCPaging (Magazines)", "LabMagazinesMVCPaging", "Filters", null, new { @class = "btn btn-primary" })
    </p>
</div>

MVC3.UI.MVC/Views/Filters/LabMagazinesMVCPaging.cshtml
@*@model IEnumerable<MVC3.DATA.EF.Magazine>*@
@model PagedList.IPagedList<MVC3.DATA.EF.Magazine>
@using PagedList.Mvc;

@{
    ViewBag.Title = "LabMagazinesMVCPaging";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("LabMagazinesMVCPaging", "Filters", FormMethod.Get))
{
    <p class="pull-right text-right">
        @Html.TextBox("searchString", ViewBag.CurrentFilter as string, new { placeholder = "Search Title" })
        <input type="submit" value="Search" class="btn btn-primary" />
    </p>
}

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("LabMagazinesMVCPaging", new { page, currentFilter = ViewBag.CurrentFilter }))

    @if (Model.Count == 0)
    {
        <p class="alert alert-warning">
            No Results meet your criteria
        </p>
    }
    else
    {


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().MagazineTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().IssuesPerYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().PricePerYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Circulation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().PublishRate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MagazineTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IssuesPerYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PricePerYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Circulation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublishRate)
            </td>
        </tr>
    }

</table>
    }

MVC3.UI.MVC/Views/Filters/LabMagazinesQS.cshtml
@model IEnumerable<MVC3.DATA.EF.Magazine>

@{
    ViewBag.Title = "Magazine List (LAB)";
}

<h2>@ViewBag.Title</h2>

<div class="row panel panel-primary">
    <br />
    <form action="LabMagazinesQS" method="get" class="form-horizontal pull-left">
        <div class="form-group">
            <div class="col-xs-offset-1 col-xs-11 col-sm-2">
                <label for="searchFilter">Search</label>
            </div>
            <div class="col-xs-offset-1 col-xs-11 col-sm-5">
                <input type="text" name="searchFilter" />
            </div>
            <div class="col-xs-offset-1 col-xs-11 col-sm-2">
                <input type="submit" value="Go!" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>


@*This is optional code for a dropdown menu select*@
@*<div class="row panel panel-primary">
    <br />
    <form action="LabMagazinesQS" class="form-horizontal">
        <div class="form-group">
            <div class="col-xs-offset-1">
                <label for="searchFilter">Search Category</label>
            </div>
            <div class="col-md-5">
                @{ 
                    MVC3.DATA.EF.BookStorePlusEntities ctx = new MVC3.DATA.EF.BookStorePlusEntities();
                    var allCategories = from m in ctx.Magazines
                                        select m.Category;
                    var uniqueCategories = allCategories.Distinct();
                }

                <select name="category" class="form-control">
                    <option>Please Choose a Category</option>
                    @foreach(var x in uniqueCategories)
                    {
                        <option>@x</option>
                    }
                </select>
            </div>
            <div class="col-md-2">
                <input type="submit" class="main-button" value="Search"/>
            </div>
            <div class="col-md-2">
                <div class="btn btn-danger">@Html.ActionLink("Reset", "Index", null, new { @class = "reset-button" })</div>
            </div>
        </div>
    </form>
</div>*@

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MagazineTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IssuesPerYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PricePerYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Circulation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PublishRate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MagazineTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IssuesPerYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PricePerYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Circulation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PublishRate)
        </td>
    </tr>
}

</table>