MVC3.UI.MVC/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC3.DATA.EF;

namespace MVC3.UI.MVC.Controllers
{
    public class AuthorsController : Controller
    {
        private BookStorePlusEntities db = new BookStorePlusEntities();

        // GET: Authors
        public ActionResult Index()
        {
            return View(db.Authors.ToList());
        }

        // GET: Authors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: Authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AuthorID,FirstName,LastName,City,State,ZipCode,Country")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Authors.Add(author);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(author);
        }

        // GET: Authors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AuthorID,FirstName,LastName,City,State,ZipCode,Country")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Author author = db.Authors.Find(id);
            db.Authors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC3.UI.MVC/Controllers/PublishersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC3.DATA.EF;

namespace MVC3.UI.MVC.Controllers
{
    public class PublishersController : Controller
    {
        private BookStorePlusEntities db = new BookStorePlusEntities();

        #region AJAX Delete
        //Delete Publisher record, return only json data on id and confirmation
        [HttpPost]
        public JsonResult AjaxDelete(int id)
        {
            //Retrieve that publisher from db
            Publisher pub = db.Publishers.Find(id);

            //Remove the publisher
            db.Publishers.Remove(pub);

            //Save Changes to the DB
            db.SaveChanges();

            //Create a message to send back to the UI as a JSON result
            var message = $"Deleted Publisher {pub.PublisherName} from the database!";
            return Json(
                new
                {
                    id = id,
                    message = message
                });
        }

        #endregion

        #region AJAX Details
        [HttpGet]
        public PartialViewResult PublisherDetails(int id)
        {
            //Retrieve the publisher by its id
            Publisher pub = db.Publishers.Find(id);

            //Return a partial view to the browser with the publisher object
            return PartialView(pub);

            //Right click and add a partial view
            //scaffold to details
            //select partial view
        }

        #endregion

        #region AJAX Create
        //Add Publisher to database via AJAX and return results
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult PublisherCreate(Publisher publisher)
        {
            db.Publishers.Add(publisher);
            db.SaveChanges();
            return Json(publisher);
        }

        #endregion

        #region AJAX Edit - GET (Show the form) and POST (process the form)
        public PartialViewResult PublisherEdit(int id)
        {
            Publisher pub = db.Publishers.Find(id);
            return PartialView(pub);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult AjaxEdit(Publisher publisher)
        {
            db.Entry(publisher).State = EntityState.Modified;
            db.SaveChanges();
            return Json(publisher);
        }

        #endregion

        // GET: Publishers
        public ActionResult Index()
        {
            return View(db.Publishers.ToList());
        }

        // GET: Publishers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publisher publisher = db.Publishers.Find(id);
            if (publisher == null)
            {
                return HttpNotFound();
            }
            return View(publisher);
        }

        // GET: Publishers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Publishers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PublisherID,PublisherName,City,State,IsActive")] Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                db.Publishers.Add(publisher);
                //This Controller will FAIL if the State column has more than 2 characters typed into it. So, either edit it or expect it
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(publisher);
        }

        // GET: Publishers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publisher publisher = db.Publishers.Find(id);
            if (publisher == null)
            {
                return HttpNotFound();
            }
            return View(publisher);
        }

        // POST: Publishers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PublisherID,PublisherName,City,State,IsActive")] Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                db.Entry(publisher).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(publisher);
        }

        // GET: Publishers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publisher publisher = db.Publishers.Find(id);
            if (publisher == null)
            {
                return HttpNotFound();
            }
            return View(publisher);
        }

        // POST: Publishers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Publisher publisher = db.Publishers.Find(id);
            db.Publishers.Remove(publisher);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC3.UI.MVC/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC3.UI.MVC.Models;

namespace MVC3.UI.MVC.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart
        public ActionResult Index()
        {
            //Create a local version of the shopping cart from the Sess(global) version
            //If the value is null of the counmtr is 0 create an empty instance and provide no cart items
            var shoppingCart = (Dictionary<int, ShoppingCartViewModel>)Session["cart"];

            if(shoppingCart == null || shoppingCart.Count == 0)
            {
                //new empty instance of the local shoppingCart to pass to the View
                //(strongly typed view MUST have an instance of our shopping cart in order to load)
                shoppingCart = new Dictionary<int, ShoppingCartViewModel>();
                ViewBag.Message = "There are no books in your cart.";
            }
            else
            {
                ViewBag.Message = null;
            }

            return View(shoppingCart);
        }

        public ActionResult UpdateCart(int bookID, int qty)
        {
            //retrieve the cart from session and assign it to our local dictionary
            Dictionary<int, ShoppingCartViewModel> shoppingCart = (Dictionary<int, ShoppingCartViewModel>)Session["cart"];

            //Update the quantity in the local storage
            shoppingCart[bookID].qty = qty;

            //Return the local cart to session
            Session["cart"] = shoppingCart;

            //Logic to display a message if they update to NO items in their cart
            if(shoppingCart.Count == 0)
            {
                ViewBag.Message = "There are no books in your cart.";
            }

            //return View("index" - the code in the index action WILL NOT run - the cart totals will not change
            //in fact, it may even cause an error because no shoppingCArt (dictionary) was sent to the view

            //RedirectAction to the index so that the code runs in that methods and reutns the view with the updated data
            return RedirectToAction("Index");
        }

        public ActionResult RemoveFromCart(int id)
        {
            //retrieve the cart from session and assign it to our local dictionary
            Dictionary<int, ShoppingCartViewModel> shoppingCart = (Dictionary<int, ShoppingCartViewModel>)Session["cart"];

            //call the remove() method from the dictionary class
            shoppingCart.Remove(id);

            //Setup the viewbag message for no results
            if(shoppingCart.Count == 0)
            {
                ViewBag.Message = "There are no books in your cart.";
                Session["cart"] = null;
            }

            return RedirectToAction("Index");
        }
    }
}

MVC3.UI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>@ViewBag.Title - MVC3 Site</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Lato:700%7CMontserrat:400,600" rel="stylesheet">

	@*MOVED TO BundleConfig.cs
		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="css/bootstrap.min.css" />

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href="css/font-awesome.min.css">

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href="css/style.css" />*@

	@*ADDED jQueryUI CSS CDN - note: themenames are swappable.*@
	@*find names at jqueryui.com/themeroller, gallyery tab (like excite-bike, south-street or sunny)*@
	@*<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">*@
	<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/south-street/jquery-ui.css">

	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")

	@*Give pages option to customize head*@
	@RenderSection("htmlHead", required: false)


	@*REMOVED, using modernizr bundle above from original Layout instead
			<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->*@

</head>
<body>

	<!-- Header -->
	<header id="header" class="transparent-nav">
		<div class="container">

			<div class="navbar-header">
				<!-- Logo -->
				<div class="navbar-brand">
					@*UPDATE paths below A & IMG
						<a class="logo" href="index.html">*@
					<a class="logo" href="~/Home/Index">
						@*<img src="./img/logo-alt.png" alt="logo">*@
						<img src="~/Content/img/logo-alt.png" alt="logo">
					</a>
				</div>
				<!-- /Logo -->
				<!-- Mobile toggle -->
				<button class="navbar-toggle">
					<span></span>
				</button>
				<!-- /Mobile toggle -->
			</div>

			<!-- Navigation -->
			<nav id="nav">
				<ul class="main-menu nav navbar-nav navbar-right">
					@*converted this original nav bar
						<li><a href="index.html">Home</a></li>
						<li><a href="#">About</a></li>
						<li><a href="#">Courses</a></li>
						<li><a href="blog.html">Blog</a></li>
						<li><a href="contact.html">Contact</a></li>*@
					@* HOME is optional-logo will get you to default, no-content page.
						<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
					<li>@Html.ActionLink("Books", "Index", "Books")</li>
					<li>@Html.ActionLink("Filters", "Index", "Filters")</li>
					<li>@Html.ActionLink("Ajax", "Index", "Publishers")</li>

					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Account</a>
						<div class="dropdown-menu" style="background-color: lightgray;">
							@Html.ActionLink("Cart", "Index", "ShoppingCart", null, new { @class = "dropdown-item" })

							@if (Request.IsAuthenticated && User.IsInRole("Admin"))
							{
								@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin", null, new { @class = "dropdown-item" })
								@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin", null, new { @class = "dropdown-item" })
							}
						</div>
					</li>

                    @if(Session["cart"] != null)
                    {
                        //Total Quantity of items in a cart
                        var cart = (Dictionary<int, MVC3.UI.MVC.Models.ShoppingCartViewModel>)Session["cart"];
                        var cartCount = cart.Sum(x => x.Value.qty);
                        <li>
                            <a href="@Url.Action("Index", "ShoppingCart")">
                                <i class="fa fa-shopping-cart"></i>
                                <!--Superscript Text-->
                                <sup><span class="cartCount">@cartCount</span></sup>
                            </a>
                        </li>
                    }

					@Html.Partial("_LoginPartial")
				</ul>
			</nav>
			<!-- /Navigation -->

		</div>
	</header>
	<!-- /Header -->
	<!-- Home -->
	<div id="home" class="hero-area">

		<!-- Backgound Image -->
		@*UPDATE path
			<div class="bg-image bg-parallax overlay" style="background-image:url(./img/home-background.jpg)"></div>*@
		<div class="bg-image bg-parallax overlay" style="background-image:url(@Url.Content("~/Content/img/home-background.jpg"))"></div>
		<!-- /Backgound Image -->

		<div class="home-wrapper">
			<div class="container">
				<div class="row">
					<div class="col-md-8">
						@*UPDATED CONTENT
							<h1 class="white-text">Edusite Free Online Training Courses</h1>
							<p class="lead white-text">Libris vivendo eloquentiam ex ius, nec id splendide abhorreant, eu pro alii error homero.</p>*@
						<h1 class="white-text">MVC3 Site</h1>
						<p class="lead white-text">Paging & Filtering, Shopping Cart, AJAX, Web Services, Error Handling</p>

						<a class="main-button icon-button" href="http://centriq.com">Get Started!</a>
					</div>
				</div>
			</div>
		</div>

	</div>
	<!-- /Home -->
	@*ADDED this div#main.section for RenderBody()*@
	<div id="main" class="section">
		<div class="container">
			@*ADDED notification for AJAX*@
            <!--This first <div> is used for the AJAX messaging associated with publishers. It will display whatever message we send based off the action being taken-->
			<div id="MessageDisplay" class="row">
				<div class="col-md-10 col-md-offset-1" id="MessageContent"></div>
			</div>

			<div class="row">
				@RenderBody()
			</div>
		</div>

	</div>

	<!-- Footer -->
	<footer id="footer" class="section">

		<!-- container -->
		<div class="container">

			<!-- row -->
			<div class="row">

				<!-- footer logo -->
				<div class="col-md-2">
					<div class="footer-logo">
						@*UPDATE paths below A & IMG
							<a class="logo" href="index.html">*@
						<a class="logo" href="~/Home/Index">

							@*<img src="./img/logo.png" alt="logo">*@
							<img src="~/Content/img/logo.png" alt="logo">
						</a>
					</div>
				</div>
				<!-- footer logo -->
				<!-- footer nav -->
				<div class="col-md-10">
					<ul class="footer-nav">
						<li>@Html.ActionLink("Books", "Index", "Books")</li>
						<li>@Html.ActionLink("Filters", "Index", "Filters")</li>
						<li>@Html.ActionLink("Ajax-Publishers", "Index", "Publishers")</li>
						<li>@Html.ActionLink("Web Service-Authors", "Index", "Authors")</li>
						<li>@Html.ActionLink("Errors", "Index", "Errors")</li>
					</ul>
				</div>
				<!-- /footer nav -->

			</div>
			<!-- /row -->
			<!-- row -->
			<div id="bottom-footer" class="row">

				<!-- social -->
				<div class="col-md-4 col-md-push-8">
					<ul class="footer-social">
						<li><a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li>
						<li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
						<li><a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a></li>
						<li><a href="#" class="instagram"><i class="fa fa-instagram"></i></a></li>
						<li><a href="#" class="youtube"><i class="fa fa-youtube"></i></a></li>
						<li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
					</ul>
				</div>
				<!-- /social -->
				<!-- copyright -->
				<div class="col-md-8 col-md-pull-4">
					<div class="footer-copyright">
						<span>
							@* REPLACED from layout
								&copy; Copyright 2018.*@
							&copy; @DateTime.Now.Year - MVC3Site.
							All Rights Reserved. | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com">Colorlib</a>
						</span>
					</div>
				</div>
				<!-- /copyright -->

			</div>
			<!-- row -->

		</div>
		<!-- /container -->

	</footer>
	<!-- /Footer -->
	<!-- preloader -->
	<div id='preloader'><div class='preloader'></div></div>
	<!-- /preloader -->
	<!-- jQuery Plugins -->
	@*MOVED these script references to BundleConfig.cs and referenced thru layout-copy-adapt code below.
		<script type="text/javascript" src="js/jquery.min.js"></script>
		<script type="text/javascript" src="js/bootstrap.min.js"></script>
		<script type="text/javascript" src="js/main.js"></script>*@

	@Scripts.Render("~/bundles/template")

	<!--ADDEDjQuery UI CDN-->
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

	<!--ADDED jQuery Ajax CDN-->
	<script src="https://cdn.jsdelivr.net/jquery.ajax.unobtrusive/3.2.4/jquery.unobtrusive-ajax.min.js"></script>


	@RenderSection("scripts", required: false)

</body>
</html>

MVC3.UI.MVC/Views/Shared/_OriginalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>